module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(
    'Teams',
    [
      {
        city: 'Atlanta',
        name: 'Hawks',
        key: 'ATL',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Brooklyn',
        name: 'Nets',
        key: 'BKN',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Boston',
        name: 'Celtics',
        key: 'BOS',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Charlotte',
        name: 'Hornets',
        key: 'CHA',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Chicago',
        name: 'Bulls',
        key: 'CHI',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Cleveland',
        name: 'Cavaliers',
        key: 'CLE',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Detroit',
        name: 'Pistons',
        key: 'DET',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Indiana',
        name: 'Pacers',
        key: 'IND',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Miami',
        name: 'Heat',
        key: 'MIA',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Milwaukee',
        name: 'Bucks',
        key: 'MIL',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Mew York',
        name: 'Knicks',
        key: 'NYK',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Orlando',
        name: 'Magic',
        key: 'ORL',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Philadelphia',
        name: '76ers',
        key: 'PHI',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Toronto',
        name: 'Raptors',
        key: 'TOR',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Washington',
        name: 'Wizards',
        key: 'WAS',
        conference: 'E',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Dallas',
        name: 'Mavericks',
        key: 'DAL',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Denver',
        name: 'Nuggets',
        key: 'DEN',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Golden State',
        name: 'Warriors',
        key: 'GSW',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Houston',
        name: 'Rockets',
        key: 'HOU',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Los Angeles',
        name: 'Clippers',
        key: 'LAC',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Los Angeles',
        name: 'Lakers',
        key: 'LAL',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Memphis',
        name: 'Grizzlies',
        key: 'MEM',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Minnesota',
        name: 'Timberwolves',
        key: 'MIN',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'New Orleans',
        name: 'Pelicans',
        key: 'NOP',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Oklahoma City',
        name: 'Thunder',
        key: 'OKC',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Phoenix',
        name: 'Suns',
        key: 'PHO',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Portland',
        name: 'Trail Blazers',
        key: 'PTB',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Sacramento',
        name: 'Kings',
        key: 'SAC',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'San Antonio',
        name: 'Spurs',
        key: 'SAS',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Utah',
        name: 'Jazz',
        key: 'UTA',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'Seattle',
        name: 'SuperSonics',
        key: 'SEA',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city: 'New Orleans/Oklahoma City',
        name: 'Hornets',
        key: 'NOK',
        conference: 'W',
        startSeason: 1234,
        endSeason: 1234,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {},
  ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Locations', null, {}),
};
